// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCYPKgDawbVEmLvKBXhuk35c4q7tGONyk',
    appId: '1:880375692072:web:61bc62b77bad9b35d2ee1d',
    messagingSenderId: '880375692072',
    projectId: 'rpi-portail',
    authDomain: 'rpi-portail.firebaseapp.com',
    storageBucket: 'rpi-portail.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC6wp58J8I0DEQoPHgePwNjswZ2vmqZLk',
    appId: '1:446423568154:android:4aeb439e7fb8eef51fe6a3',
    messagingSenderId: '446423568154',
    projectId: 'rpi-sav-app',
    storageBucket: 'rpi-sav-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC82qUdtnpYh8HNmBPFqGDSjgFSXbLyh3g',
    appId: '1:446423568154:ios:550f29cba0b3f31c1fe6a3',
    messagingSenderId: '446423568154',
    projectId: 'rpi-sav-app',
    storageBucket: 'rpi-sav-app.firebasestorage.app',
    iosBundleId: 'com.rpimenuiserie.rpiSavApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC82qUdtnpYh8HNmBPFqGDSjgFSXbLyh3g',
    appId: '1:446423568154:ios:550f29cba0b3f31c1fe6a3',
    messagingSenderId: '446423568154',
    projectId: 'rpi-sav-app',
    storageBucket: 'rpi-sav-app.firebasestorage.app',
    iosBundleId: 'com.rpimenuiserie.rpiSavApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDERPWm8zGimOJCpVvK6B5rp7Xg12m5yOw',
    appId: '1:446423568154:web:ed9cb6f4aca309041fe6a3',
    messagingSenderId: '446423568154',
    projectId: 'rpi-sav-app',
    authDomain: 'rpi-sav-app.firebaseapp.com',
    storageBucket: 'rpi-sav-app.firebasestorage.app',
    measurementId: 'G-90JY9G1MN2',
  );
}
